version: '3.6'
services:
    zookeeper:
        image: 'wurstmeister/zookeeper:latest'
        ports:
            - '2181:2181'
    kafka:
        image: 'wurstmeister/kafka:latest'
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    postgres-announcement:
        container_name: postgres-db-announcement
        image: postgres:9.5
        volumes:
            - /postgresql/data
        environment:
            - POSTGRES_PASSWORD=announcement
            - POSTGRES_USER=announcementservice
            - POSTGRES_DB=announcement
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

    blablamove-announcement:
        build:
            context: services/announcement
            dockerfile: docker/Dockerfile
        image: al-blablamove-announcement
        container_name: blablamove-announcement
        ports:
            - '127.0.0.1:8080:8080'
        links:
            - kafka
            - postgres-announcement
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'

    postgres-accounting:
        container_name: postgres-db-accounting
        image: postgres:9.5
        volumes:
            - /postgresql/data
        environment:
            - POSTGRES_PASSWORD=accounting
            - POSTGRES_USER=accountingservice
            - POSTGRES_DB=accounting
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5433:5432

    blablamove-accounting:
        build:
            context: services/accounting
            dockerfile: docker/Dockerfile
        image: al-blablamove-accounting
        container_name: blablamove-accounting
        ports:
            - '127.0.0.1:8081:8080'
        links:
            - kafka
            - postgres-accounting
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'

    blablamove-billing:
        build:
            context: services/billing
            dockerfile: docker/Dockerfile
        image: al-blablamove-billing
        container_name: blablamove-billing
        ports:
            - '127.0.0.1:8082:8080'
        links:
            - kafka
            - postgres-billing
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'

    postgres-billing:
        container_name: postgres-db-billing
        image: postgres:9.5
        volumes:
            - /postgresql/data
        environment:
            - POSTGRES_PASSWORD=billing
            - POSTGRES_USER=billingservice
            - POSTGRES_DB=billing
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5434:5432

    blablamove-matching:
        build:
            context: services/matching
            dockerfile: docker/Dockerfile
        image: al-blablamove-matching
        container_name: blablamove-matching
        ports:
            - '127.0.0.1:8084:8080'
        links:
            - kafka
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'

    blablamove-tracking:
        build:
            context: services/tracking
            dockerfile: docker/Dockerfile
        image: al-blablamove-tracking
        container_name: blablamove-tracking
        ports:
            - '127.0.0.1:8085:8080'
        links:
            - kafka
            - postgres-tracking
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'

    postgres-tracking:
        container_name: postgres-db-tracking
        image: postgres:9.5
        volumes:
            - /postgresql/data
        environment:
            - POSTGRES_PASSWORD=tracking
            - POSTGRES_USER=trackingservice
            - POSTGRES_DB=tracking
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5435:5432

volumes:
    postgres-db-announcement: {}
    postgres-db-accounting: {}
    postgres-db-billing: {}
    postgres-db-tracking: {}